export const actionTypes = {
  ADD_MENU_LIST: "ADD_MENU_LIST",
  ADD_ITEMS_QUANTITY: "ADD_ITEMS_QUANTITY",
  VEG_FILTER_RESULT: "VEG_FILTER_RESULT",
  REMOVE_ITEMS_QUANTITY: "REMOVE_ITEMS_QUANTITY",
};
